name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  build-processor:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory:
          - processor
          - job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.directory }}

      - name: Run ESLint check
        run: npm run lint
        working-directory: ${{ matrix.directory }}

      - name: Run Prettier check
        run: npm run prettier:check
        working-directory: ${{ matrix.directory }}

      - name: Build project
        run: npm run build
        working-directory: ${{ matrix.directory }}

      - name: Run tests
        run: npm run test
        working-directory: ${{ matrix.directory }}

      - name: Archive junit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: processor/junit-report.xml

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: processor/coverage/lcov.info

  build-application:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: application

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint check
        run: yarn run lint

      - name: Run Prettier check
        run: yarn run format

      - name: Build project
        run: yarn run build

      - name: Run tests
        run: yarn run test
